import {
  Box,
  Typography,
  Modal,
  IconButton,
  alpha,
} from "@mui/material";
import CloseIcon from "@mui/icons-material/Close";
import QuizIcon from "@mui/icons-material/Quiz";
import { useState } from "react";
import { Controller, useForm, SubmitHandler } from "react-hook-form";
import {
  TextField,
  MenuItem,
  Button,
  Select,
  FormControl,
  CircularProgress,
  Tabs,
  Tab,
  FormControlLabel,
  Checkbox,
} from "@mui/material";

interface GenerateQuizModalProps {
  isOpen: boolean;
  onClose: () => void;
}

interface IQuizFormData {
  sourceText?: string;
  sourceFile?: string;
  videoUrl?: string;
  videoSourceType?: "upload" | "url";
  autoGenerateTitle?: boolean;
  autoGenerateDescription?: boolean;
  generateTranscript?: boolean;
  focusKeyword?: string;
  questionCount?: number;
  difficultyLevel?: string;
  optionsCount?: number;
  contentType?: string;
}

const modalStyle = {
  position: "absolute" as "absolute",
  top: "50%",
  left: "50%",
  transform: "translate(-50%, -50%)",
  width: { xs: "90%", sm: 600, md: 700 },
  maxWidth: 700,
  bgcolor: "background.paper",
  borderRadius: "20px",
  boxShadow:
    "0 20px 60px rgba(15,23,42,0.12), 0 8px 24px rgba(15,23,42,0.08)",
  maxHeight: "90vh",
  display: "flex",
  flexDirection: "column",
  overflow: "hidden",
  outline: "none",
};

const initialSourceText = `GitHub has transformed software development into a globally collaborative process. As the world's leading platform for code hosting and version control, it enables millions of developers to work on projects concurrently, manage changes efficiently, and build open-source communities.

Following its acquisition by Microsoft, GitHub has expanded its services significantly, moving beyond simple Git hosting to offer advanced DevOps tools like GitHub Actions for continuous integration/continuous delivery (CI/CD) and GitHub Copilot for AI-assisted coding. This focus solidifies its role as the central hub for the entire software development lifecycle, from planning and coding to deployment and security.`;

export const GenerateQuizModal: React.FC<GenerateQuizModalProps> = ({
  isOpen,
  onClose,
}) => {
  const [activeTab, setActiveTab] = useState<"text" | "file" | "video">("text");
  const [videoSourceType, setVideoSourceType] = useState<"upload" | "url">("upload");
  const [isLoading, setIsLoading] = useState(false);

  const {
    control,
    handleSubmit,
    formState: { errors },
    reset,
  } = useForm<IQuizFormData>({
    defaultValues: {
      sourceText: initialSourceText,
      videoUrl: "",
      videoSourceType: "upload",
      autoGenerateTitle: true,
      autoGenerateDescription: true,
      generateTranscript: false,
      focusKeyword: "",
      questionCount: 3,
      difficultyLevel: "Medium",
      optionsCount: 4,
      contentType: "MCQ",
    },
    mode: "onChange",
  });

  const onSubmit: SubmitHandler<IQuizFormData> = async (data) => {
    console.log("🚀 Generate Quiz Submitted:", data);
    setIsLoading(true);

    try {
      // TODO: Replace with actual API call
      // Simulate API call
      await new Promise((resolve) => setTimeout(resolve, 2000));

      console.log("✅ Quiz generated successfully");
      // Handle success (e.g., show notification, redirect, etc.)
      onClose();
      reset();
    } catch (error) {
      console.error("❌ Error generating quiz:", error);
    } finally {
      setIsLoading(false);
    }
  };

  const handleClose = () => {
    if (!isLoading) {
      onClose();
      reset();
    }
  };

  return (
    <Modal
      open={isOpen}
      onClose={handleClose}
      aria-labelledby="generate-quiz-modal-title"
      aria-describedby="generate-quiz-modal-description"
      sx={{
        backdropFilter: "blur(4px)",
        "& .MuiBackdrop-root": {
          bgcolor: alpha("#000", 0.5),
        },
      }}
    >
      <Box sx={modalStyle}>
        {/* Modal Header */}
        <Box
          sx={{
            display: "flex",
            justifyContent: "space-between",
            alignItems: "center",
            p: 3,
            pb: 2.5,
            borderBottom: "1px solid rgba(148,163,184,0.12)",
            bgcolor: "#FFFFFF",
          }}
        >
          <Box sx={{ display: "flex", alignItems: "center", gap: 1.5 }}>
            <Box
              sx={{
                width: 40,
                height: 40,
                borderRadius: "10px",
                bgcolor: "#EEF2FF",
                display: "flex",
                alignItems: "center",
                justifyContent: "center",
              }}
            >
              <QuizIcon sx={{ fontSize: 22, color: "#4F39F6" }} />
            </Box>
            <Box>
              <Typography
                id="generate-quiz-modal-title"
                variant="h6"
                component="h2"
                sx={{
                  fontWeight: 700,
                  fontSize: "20px",
                  color: "#0f172a",
                  lineHeight: 1.2,
                }}
              >
                Generate Quiz
              </Typography>
              <Typography
                variant="body2"
                sx={{
                  fontSize: "13px",
                  color: "#64748b",
                  mt: 0.25,
                }}
              >
                AI-powered quiz generation
              </Typography>
            </Box>
          </Box>
          <IconButton
            onClick={handleClose}
            disabled={isLoading}
            sx={{
              color: "#64748b",
              "&:hover": {
                bgcolor: alpha("#64748b", 0.1),
                color: "#0f172a",
              },
              transition: "all 0.2s ease",
            }}
          >
            <CloseIcon />
          </IconButton>
        </Box>

        {/* Modal Content - Scrollable */}
        <Box
          sx={{
            flex: 1,
            overflowY: "auto",
            p: 3,
            bgcolor: "#FFFFFF",
            "&::-webkit-scrollbar": {
              width: "6px",
            },
            "&::-webkit-scrollbar-track": {
              bgcolor: "transparent",
            },
            "&::-webkit-scrollbar-thumb": {
              bgcolor: alpha("#64748b", 0.3),
              borderRadius: "10px",
              "&:hover": {
                bgcolor: alpha("#64748b", 0.5),
              },
            },
          }}
        >
          <form noValidate onSubmit={handleSubmit(onSubmit)}>
            {/* Section Title */}
            <Typography
              variant="h6"
              sx={{ fontWeight: 600, mb: 3, color: "#0f172a" }}
            >
              AI Configuration
            </Typography>

            {/* Tabs for Text / File / Video */}
            <Tabs
              value={activeTab}
              onChange={(_, newValue) => setActiveTab(newValue)}
              sx={{ mb: 3 }}
            >
              <Tab label="Text" value="text" />
              <Tab label="File" value="file" />
              <Tab label="Video" value="video" />
            </Tabs>

            {/* TEXT TAB */}
            {activeTab === "text" && (
              <Box>
                <Typography
                  variant="body2"
                  sx={{ fontWeight: 500, mb: 1, color: "text.primary" }}
                >
                  Source Material:
                </Typography>
                <Controller
                  name="sourceText"
                  control={control}
                  rules={{ required: "Source material is required" }}
                  render={({ field }) => (
                    <TextField
                      {...field}
                      fullWidth
                      multiline
                      minRows={6}
                      maxRows={12}
                      placeholder="Paste your source material here..."
                      error={!!errors.sourceText}
                      helperText={errors.sourceText?.message}
                      sx={{ mb: 3 }}
                    />
                  )}
                />
              </Box>
            )}

            {/* FILE TAB */}
            {activeTab === "file" && (
              <Box>
                <Typography
                  variant="body2"
                  sx={{ fontWeight: 500, mb: 1, color: "text.primary" }}
                >
                  File Material:
                </Typography>
                <Controller
                  name="sourceFile"
                  control={control}
                  rules={{ required: "Source material file is required" }}
                  render={({ field }) => (
                    <TextField
                      {...field}
                      type="file"
                      fullWidth
                      inputProps={{ accept: ".txt,.pdf,.doc,.docx,.csv,.json,.md" }}
                      error={!!errors.sourceFile}
                      helperText={errors.sourceFile?.message}
                      sx={{ mb: 3 }}
                    />
                  )}
                />
              </Box>
            )}

            {/* VIDEO TAB */}
            {activeTab === "video" && (
              <Box>
                <Typography
                  variant="body2"
                  sx={{ fontWeight: 500, mb: 1, color: "text.primary" }}
                >
                  Video Source:
                </Typography>
                <Tabs
                  value={videoSourceType}
                  onChange={(_, newValue) => setVideoSourceType(newValue)}
                  sx={{ mb: 2 }}
                >
                  <Tab label="Upload Video" value="upload" />
                  <Tab label="Video URL" value="url" />
                </Tabs>

                {videoSourceType === "upload" && (
                  <Box
                    sx={{
                      border: "2px dashed",
                      borderColor: "divider",
                      borderRadius: 2,
                      p: 4,
                      textAlign: "center",
                      mb: 3,
                      cursor: "pointer",
                      bgcolor: "grey.50",
                      transition: "all 0.2s",
                      "&:hover": {
                        borderColor: "primary.main",
                        bgcolor: "primary.50",
                      },
                    }}
                  >
                    <Typography
                      variant="body1"
                      color="text.secondary"
                      sx={{ mb: 0.5 }}
                    >
                      Click to upload or drag and drop
                    </Typography>
                    <Typography variant="caption" color="text.secondary">
                      MP4, MOV, AVI (MAX. 500MB)
                    </Typography>
                  </Box>
                )}

                {videoSourceType === "url" && (
                  <Controller
                    name="videoUrl"
                    control={control}
                    rules={{ required: "Video URL is required" }}
                    render={({ field }) => (
                      <TextField
                        {...field}
                        fullWidth
                        label="Video URL"
                        placeholder="https://example.com/video.mp4"
                        error={!!errors.videoUrl}
                        helperText={errors.videoUrl?.message}
                        sx={{ mb: 3 }}
                      />
                    )}
                  />
                )}

                <Box sx={{ mb: 3 }}>
                  <Controller
                    name="autoGenerateTitle"
                    control={control}
                    render={({ field }) => (
                      <FormControlLabel
                        control={<Checkbox {...field} checked={field.value} />}
                        label="Auto-generate title from video"
                        sx={{ display: "block", mb: 1 }}
                      />
                    )}
                  />
                  <Controller
                    name="autoGenerateDescription"
                    control={control}
                    render={({ field }) => (
                      <FormControlLabel
                        control={<Checkbox {...field} checked={field.value} />}
                        label="Auto-generate description from video"
                        sx={{ display: "block", mb: 1 }}
                      />
                    )}
                  />
                  <Controller
                    name="generateTranscript"
                    control={control}
                    render={({ field }) => (
                      <FormControlLabel
                        control={<Checkbox {...field} checked={field.value} />}
                        label="Generate video transcript"
                        sx={{ display: "block" }}
                      />
                    )}
                  />
                </Box>
              </Box>
            )}

            {/* FOCUS KEYWORD */}
            <Typography
              variant="body2"
              sx={{ fontWeight: 500, mb: 1, color: "text.primary" }}
            >
              Focus Keyword / Topic:
            </Typography>
            <Controller
              name="focusKeyword"
              control={control}
              render={({ field }) => (
                <TextField
                  {...field}
                  fullWidth
                  placeholder="e.g., GitHub Actions CI/CD or Repository Forks"
                  sx={{ mb: 3 }}
                />
              )}
            />

            {/* CONTENT TYPE */}
            <Typography
              variant="body2"
              sx={{ fontWeight: 500, mb: 1, color: "text.primary" }}
            >
              Content Type:
            </Typography>
            <FormControl fullWidth sx={{ mb: 3 }}>
              <Controller
                name="contentType"
                control={control}
                render={({ field }) => (
                  <Select {...field}>
                    <MenuItem value="MCQ">Multiple Choice (MCQ)</MenuItem>
                  </Select>
                )}
              />
            </FormControl>

            {/* QUESTION COUNT & DIFFICULTY LEVEL */}
            <Box sx={{ display: "flex", gap: 2, mb: 3 }}>
              <Box sx={{ flex: 1 }}>
                <Typography
                  variant="body2"
                  sx={{ fontWeight: 500, mb: 1, color: "text.primary" }}
                >
                  Question Count:
                </Typography>
                <Controller
                  name="questionCount"
                  control={control}
                  render={({ field }) => (
                    <FormControl fullWidth>
                      <Select {...field}>
                        {[1, 2, 3, 4, 5].map((count) => (
                          <MenuItem key={count} value={count}>
                            {count}
                          </MenuItem>
                        ))}
                      </Select>
                    </FormControl>
                  )}
                />
              </Box>

              <Box sx={{ flex: 1 }}>
                <Typography
                  variant="body2"
                  sx={{ fontWeight: 500, mb: 1, color: "text.primary" }}
                >
                  Difficulty Level:
                </Typography>
                <Controller
                  name="difficultyLevel"
                  control={control}
                  render={({ field }) => (
                    <FormControl fullWidth>
                      <Select {...field}>
                        <MenuItem value="Easy">Easy</MenuItem>
                        <MenuItem value="Medium">Medium</MenuItem>
                        <MenuItem value="Hard">Hard</MenuItem>
                      </Select>
                    </FormControl>
                  )}
                />
              </Box>
            </Box>

            {/* ACTION BUTTONS */}
            <Box sx={{ display: "flex", gap: 2, justifyContent: "flex-end", mt: 4 }}>
              <Button
                onClick={handleClose}
                variant="outlined"
                disabled={isLoading}
                sx={{ minWidth: 100 }}
              >
                Cancel
              </Button>
              <Button
                type="submit"
                variant="contained"
                disabled={isLoading}
                sx={{
                  minWidth: 160,
                  bgcolor: "#4F39F6",
                  "&:hover": {
                    bgcolor: "#3E2DC4",
                  },
                }}
              >
                {isLoading ? (
                  <>
                    <CircularProgress size={20} sx={{ mr: 1 }} color="inherit" />
                    Generating...
                  </>
                ) : (
                  "Generate with AI"
                )}
              </Button>
            </Box>
          </form>
        </Box>
      </Box>
    </Modal>
  );
};

