import { useState } from "react";
import {
  Box,
  Typography,
  TextField,
  MenuItem,
  Button,
  Select,
  FormControl,
  CircularProgress,
  FormControlLabel,
  Checkbox,
  Tabs,
  Tab,
} from "@mui/material";
import {
  TextFields as TextFieldsIcon,
  InsertDriveFile as FileIcon,
  Movie as MovieIcon,
} from "@mui/icons-material";
import UploadFileIcon from "@mui/icons-material/UploadFile";
import AutoAwesomeIcon from '@mui/icons-material/AutoAwesome';
import { Controller, useForm, SubmitHandler } from "react-hook-form";

type ContentType =
  | "multiple_choice"
  | "single_choice"
  | "fill_up"
  | "subjective"
  | "blog"
  | "video";

interface ICreateCourseContent {
  text: string;
  score: number;
  description?: string;
  correctAnswer?: string;
  options?: Array<{
    text: string;
    isCorrect: boolean;
  }>;
  blogTags?: string[];
  videoUrl?: string;
  videoFileName?: string;
  sourceText?: string;
  sourceFile?: string;
  focusKeyword?: string;
  questionCount?: number;
  difficultyLevel?: string;
  optionsCount?: number;
  blogLength?: string;
  writingTone?: string;
  videoSourceType?: "upload" | "url";
  autoGenerateTitle?: boolean;
  autoGenerateDescription?: boolean;
  generateTranscript?: boolean;
}

interface IQuestionConfiguratorProps {
  type: ContentType;
  unitId: number;
  onClose: () => void;
  onSubmit: (data: ICreateCourseContent) => Promise<void>;
  isLoading: boolean;
}

// Design system constants
const SPACING = {
  section: 4,
  field: 3,
  label: 1,
};

const TYPOGRAPHY = {
  sectionTitle: {
    variant: "h6" as const,
    sx: {
      fontWeight: 600,
      mb: SPACING.section,
      fontSize: "20px",
      color: "#101828",
      letterSpacing: "-0.02em",
    },
  },
  fieldLabel: {
    variant: "body2" as const,
    sx: {
      fontWeight: 600,
      mb: SPACING.label,
      color: "#344054",
      fontSize: "14px",
    },
  },
};

const initialSourceText = `GitHub has transformed software development into a globally collaborative process. As the world's leading platform for code hosting and version control, it enables millions of developers to work on projects concurrently, manage changes efficiently, and build open-source communities.

Following its acquisition by Microsoft, GitHub has expanded its services significantly, moving beyond simple Git hosting to offer advanced DevOps tools like GitHub Actions for continuous integration/continuous delivery (CI/CD) and GitHub Copilot for AI-assisted coding. This focus solidifies its role as the central hub for the entire software development lifecycle, from planning and coding to deployment and security.`;

const getQuestionTypeOptions = (contentType: ContentType) => {
  switch (contentType) {
    case "multiple_choice":
      return [{ value: "MCQ", label: "Multiple Choice (MCQ)" }];
    case "single_choice":
      return [{ value: "Single", label: "Single Choice" }];
    case "fill_up":
      return [{ value: "Fill", label: "Fill in the Blanks" }];
    case "subjective":
      return [{ value: "Subjective", label: "Subjective Question" }];
    case "blog":
      return [{ value: "Blog", label: "Blog Content" }];
    case "video":
      return [{ value: "Video", label: "Video Content" }];
    default:
      return [{ value: "MCQ", label: "Multiple Choice (MCQ)" }];
  }
};

const QuestionConfigurator = ({
  type,
  unitId,
  onClose,
  onSubmit: handleFormSubmit,
  isLoading,
}: IQuestionConfiguratorProps) => {
  const [videoSourceType, setVideoSourceType] = useState<"upload" | "url">(
    "upload"
  );
  const [activeTab, setActiveTab] = useState<"text" | "file" | "video">("text");

  const effectiveType: ContentType = ((): ContentType => {
    if ((type as string) === "code" || (type as string) === "mcq")
      return "multiple_choice";
    return type;
  })();

  const {
    control,
    handleSubmit,
    formState: { errors },
  } = useForm<ICreateCourseContent>({
    defaultValues: {
      sourceText: initialSourceText,
      focusKeyword: "",
      questionCount: 3,
      difficultyLevel: "Medium",
      optionsCount: 4,
      blogLength: "medium",
      writingTone: "professional",
      videoSourceType: "upload",
      videoUrl: "",
      videoFileName: "",
      autoGenerateTitle: true,
      autoGenerateDescription: true,
      generateTranscript: false,
    },
    mode: "onChange",
  });

  const onSubmit: SubmitHandler<ICreateCourseContent> = async (data) => {
    console.log("🚀 AI Configuration Submitted:", {
      contentType: effectiveType,
      unitId,
      aiConfig: data,
    });

    try {
      await handleFormSubmit(data);
    } catch (error) {
      console.error("❌ AI form submission error:", error);
    }
  };

  const questionTypeOptions = getQuestionTypeOptions(effectiveType);
  const isVideoType = effectiveType === "video";
  const isBlogType = effectiveType === "blog";
  const showQuestionCount = !["blog", "video", "subjective"].includes(
    effectiveType
  );
  const showDifficultyLevel = !["blog", "video"].includes(effectiveType);
  const showOptionsCount =
    effectiveType === "multiple_choice" || effectiveType === "single_choice";

  return (
    <form noValidate onSubmit={handleSubmit(onSubmit)}>
      {/* Section Title with Professional Styling */}
      <Box
        sx={{
          mb: 4,
          pb: 2,
          borderBottom: "2px solid #EAECF0",
        }}
      >
        <Typography variant="h6" fontWeight={600} fontSize="20px" color="#101828" letterSpacing="-0.02em">
          AI Configuration
        </Typography>
        <Typography
          variant="body2"
          sx={{
            color: "#667085",
            fontSize: "14px",
            mt: 0.5,
            p: 0,
            fontWeight: 400,
          }}
        >
          Advanced AI Settings for Quality Content Creation
        </Typography>
      </Box>

      {/* 🟩 Enhanced Tabs for Text / File / Video with Icons */}
      {!isVideoType && (
        <Box sx={{ mb: 4 }}>
          <Typography
            variant="body2"
            sx={{
              fontWeight: 600,
              mb: 0.5,
              color: "#344054",
              fontSize: "14px",
            }}
          >
            Source Material Type
          </Typography>
          <Tabs
            value={activeTab}
            onChange={(_, newValue) => setActiveTab(newValue)}
            sx={{
              mb: 3,
              "& .MuiTabs-indicator": {
                height: "3px",
                borderRadius: "3px 3px 0 0",
                backgroundColor: "#4F39F6",
              },
              "& .MuiTab-root": {
                textTransform: "none",
                fontWeight: 500,
                fontSize: "14px",
                minHeight: "48px",
                padding: "12px 24px",
                color: "#667085",
                "&.Mui-selected": {
                  color: "#4F39F6",
                  fontWeight: 600,
                },
                "&:hover": {
                  color: "#4F39F6",
                  backgroundColor: "rgba(79, 57, 246, 0.04)",
                },
              },
            }}
          >
            <Tab
              icon={<TextFieldsIcon sx={{ fontSize: "20px", mb: 0.5 }} />}
              iconPosition="start"
              label="Text"
              value="text"
              sx={{
                mr: 2,
                "& .MuiTab-iconWrapper": {
                  marginRight: "8px",
                },
              }}
            />
            <Tab
              icon={<UploadFileIcon sx={{ fontSize: "20px", mb: 0.5 }} />}
              iconPosition="start"
              label="File"
              value="file"
              sx={{
                mr: 2,
                "& .MuiTab-iconWrapper": {
                  marginRight: "8px",
                },
              }}
            />
            <Tab
              icon={<MovieIcon sx={{ fontSize: "20px", mb: 0.5 }} />}
              iconPosition="start"
              label="Video"
              value="video"
              sx={{
                "& .MuiTab-iconWrapper": {
                  marginRight: "8px",
                },
              }}
            />
          </Tabs>
        </Box>
      )}

      {/* ========== VIDEO TYPE ========== */}
      {isVideoType && (
        <>
          <Typography {...TYPOGRAPHY.fieldLabel} sx={{ mb: 2 }}>
            Video Source
          </Typography>
          <Tabs
            value={videoSourceType}
            onChange={(_, newValue) => setVideoSourceType(newValue)}
            sx={{
              mb: 3,
              "& .MuiTabs-indicator": {
                height: "3px",
                borderRadius: "3px 3px 0 0",
                backgroundColor: "#4F39F6",
              },
              "& .MuiTab-root": {
                textTransform: "none",
                fontWeight: 500,
                fontSize: "14px",
                minHeight: "48px",
                padding: "12px 24px",
                color: "#667085",
                "&.Mui-selected": {
                  color: "#4F39F6",
                  fontWeight: 600,
                },
                "&:hover": {
                  color: "#4F39F6",
                  backgroundColor: "rgba(79, 57, 246, 0.04)",
                },
              },
            }}
          >
            <Tab label="Upload Video" value="upload" />
            <Tab label="Video URL" value="url" />
          </Tabs>

          {videoSourceType === "upload" && (
            <Box
              sx={{
                border: "2px dashed",
                borderColor: "#D0D5DD",
                borderRadius: "12px",
                p: 4,
                textAlign: "center",
                mb: SPACING.field,
                cursor: "pointer",
                bgcolor: "#F9FAFB",
                transition: "all 0.2s ease",
                "&:hover": {
                  borderColor: "#4F39F6",
                  bgcolor: "#F4F3FF",
                },
              }}
            >
              <Typography
                variant="body1"
                sx={{
                  mb: 0.5,
                  color: "#344054",
                  fontWeight: 500,
                }}
              >
                Click to upload or drag and drop
              </Typography>
              <Typography
                variant="caption"
                sx={{
                  color: "#667085",
                  fontSize: "12px",
                }}
              >
                MP4, MOV, AVI (MAX. 500MB)
              </Typography>
            </Box>
          )}

          {videoSourceType === "url" && (
            <Controller
              name="videoUrl"
              control={control}
              rules={{ required: "Video URL is required" }}
              render={({ field }) => (
                <TextField
                  {...field}
                  fullWidth
                  label="Video URL"
                  placeholder="https://example.com/video.mp4"
                  error={!!errors.videoUrl}
                  helperText={errors.videoUrl?.message}
                  sx={{
                    mb: SPACING.field,
                    "& .MuiOutlinedInput-root": {
                      borderRadius: "12px",
                      "&:hover fieldset": {
                        borderColor: "#4F39F6",
                      },
                      "&.Mui-focused fieldset": {
                        borderColor: "#4F39F6",
                      },
                    },
                  }}
                />
              )}
            />
          )}

          <Box sx={{ mb: SPACING.field }}>
            <Controller
              name="autoGenerateTitle"
              control={control}
              render={({ field }) => (
                <FormControlLabel
                  control={
                    <Checkbox
                      {...field}
                      checked={field.value}
                      sx={{
                        color: "#4F39F6",
                        "&.Mui-checked": {
                          color: "#4F39F6",
                        },
                      }}
                    />
                  }
                  label="Auto-generate title from video"
                  sx={{
                    display: "block",
                    mb: 1.5,
                    "& .MuiFormControlLabel-label": {
                      fontSize: "14px",
                      color: "#344054",
                    },
                  }}
                />
              )}
            />
            <Controller
              name="autoGenerateDescription"
              control={control}
              render={({ field }) => (
                <FormControlLabel
                  control={
                    <Checkbox
                      {...field}
                      checked={field.value}
                      sx={{
                        color: "#4F39F6",
                        "&.Mui-checked": {
                          color: "#4F39F6",
                        },
                      }}
                    />
                  }
                  label="Auto-generate description from video"
                  sx={{
                    display: "block",
                    mb: 1.5,
                    "& .MuiFormControlLabel-label": {
                      fontSize: "14px",
                      color: "#344054",
                    },
                  }}
                />
              )}
            />
            <Controller
              name="generateTranscript"
              control={control}
              render={({ field }) => (
                <FormControlLabel
                  control={
                    <Checkbox
                      {...field}
                      checked={field.value}
                      sx={{
                        color: "#4F39F6",
                        "&.Mui-checked": {
                          color: "#4F39F6",
                        },
                      }}
                    />
                  }
                  label="Generate video transcript"
                  sx={{
                    display: "block",
                    "& .MuiFormControlLabel-label": {
                      fontSize: "14px",
                      color: "#344054",
                    },
                  }}
                />
              )}
            />
          </Box>
        </>
      )}

      {/* ========== NON-VIDEO TYPES: SOURCE MATERIAL ========== */}

      {/* VIDEO TAB - Duplicate section for non-video types */}
      {activeTab === "video" && !isVideoType && (
        <Box>
          <Typography {...TYPOGRAPHY.fieldLabel} sx={{ mb: 2 }}>
            Video Source
          </Typography>
          <Tabs
            value={videoSourceType}
            onChange={(_, newValue) => setVideoSourceType(newValue)}
            sx={{
              mb: 3,
              "& .MuiTabs-indicator": {
                height: "3px",
                borderRadius: "3px 3px 0 0",
                backgroundColor: "#4F39F6",
              },
              "& .MuiTab-root": {
                textTransform: "none",
                fontWeight: 500,
                fontSize: "14px",
                minHeight: "48px",
                padding: "12px 24px",
                color: "#667085",
                "&.Mui-selected": {
                  color: "#4F39F6",
                  fontWeight: 600,
                },
                "&:hover": {
                  color: "#4F39F6",
                  backgroundColor: "rgba(79, 57, 246, 0.04)",
                },
              },
            }}
          >
            <Tab label="Upload Video" value="upload" />
            <Tab label="Video URL" value="url" />
          </Tabs>

          {videoSourceType === "upload" && (
            <Box
              sx={{
                border: "2px dashed #D0D5DD",
                borderRadius: "12px",
                p: 4,
                textAlign: "center",
                mb: SPACING.field,
                cursor: "pointer",
                bgcolor: "#F9FAFB",
                transition: "all 0.2s ease",
                "&:hover": {
                  borderColor: "#4F39F6",
                  bgcolor: "#F4F3FF",
                },
              }}
            >
              <Typography
                variant="body1"
                sx={{
                  mb: 0.5,
                  color: "#344054",
                  fontWeight: 500,
                }}
              >
                Click to upload or drag and drop
              </Typography>
              <Typography
                variant="caption"
                sx={{
                  color: "#667085",
                  fontSize: "12px",
                }}
              >
                MP4, MOV, AVI (MAX. 500MB)
              </Typography>
            </Box>
          )}

          {videoSourceType === "url" && (
            <Controller
              name="videoUrl"
              control={control}
              rules={{ required: "Video URL is required" }}
              render={({ field }) => (
                <TextField
                  {...field}
                  fullWidth
                  label="Video URL"
                  placeholder="https://example.com/video.mp4"
                  error={!!errors.videoUrl}
                  helperText={errors.videoUrl?.message}
                  sx={{
                    mb: SPACING.field,
                    "& .MuiOutlinedInput-root": {
                      borderRadius: "12px",
                      "&:hover fieldset": {
                        borderColor: "#4F39F6",
                      },
                      "&.Mui-focused fieldset": {
                        borderColor: "#4F39F6",
                      },
                    },
                  }}
                />
              )}
            />
          )}

          <Box sx={{ mb: SPACING.field }}>
            <Controller
              name="autoGenerateTitle"
              control={control}
              render={({ field }) => (
                <FormControlLabel
                  control={
                    <Checkbox
                      {...field}
                      checked={field.value}
                      sx={{
                        color: "#4F39F6",
                        "&.Mui-checked": {
                          color: "#4F39F6",
                        },
                      }}
                    />
                  }
                  label="Auto-generate title from video"
                  sx={{
                    display: "block",
                    mb: 1.5,
                    "& .MuiFormControlLabel-label": {
                      fontSize: "14px",
                      color: "#344054",
                    },
                  }}
                />
              )}
            />
            <Controller
              name="autoGenerateDescription"
              control={control}
              render={({ field }) => (
                <FormControlLabel
                  control={
                    <Checkbox
                      {...field}
                      checked={field.value}
                      sx={{
                        color: "#4F39F6",
                        "&.Mui-checked": {
                          color: "#4F39F6",
                        },
                      }}
                    />
                  }
                  label="Auto-generate description from video"
                  sx={{
                    display: "block",
                    mb: 1.5,
                    "& .MuiFormControlLabel-label": {
                      fontSize: "14px",
                      color: "#344054",
                    },
                  }}
                />
              )}
            />
            <Controller
              name="generateTranscript"
              control={control}
              render={({ field }) => (
                <FormControlLabel
                  control={
                    <Checkbox
                      {...field}
                      checked={field.value}
                      sx={{
                        color: "#4F39F6",
                        "&.Mui-checked": {
                          color: "#4F39F6",
                        },
                      }}
                    />
                  }
                  label="Generate video transcript"
                  sx={{
                    display: "block",
                    "& .MuiFormControlLabel-label": {
                      fontSize: "14px",
                      color: "#344054",
                    },
                  }}
                />
              )}
            />
          </Box>
        </Box>
      )}

      {/* TEXT TAB */}
      {activeTab === "text" && !isVideoType && (
        <Box>
          <Typography {...TYPOGRAPHY.fieldLabel} sx={{ mb: 1.5 }}>
            Source Material
          </Typography>
          <Controller
            name="sourceText"
            control={control}
            rules={{ required: "Source material is required" }}
            render={({ field }) => (
              <TextField
                {...field}
                fullWidth
                multiline
                minRows={6}
                maxRows={12}
                placeholder="Paste your source material here..."
                error={!!errors.sourceText}
                helperText={errors.sourceText?.message}
                sx={{
                  mb: SPACING.field,
                  "& .MuiOutlinedInput-root": {
                    borderRadius: "12px",
                    "&:hover fieldset": {
                      borderColor: "#4F39F6",
                    },
                    "&.Mui-focused fieldset": {
                      borderColor: "#4F39F6",
                    },
                  },
                }}
              />
            )}
          />
        </Box>
      )}

      {/*   FILE TAB */}
      {activeTab === "file" && !isVideoType && (
        <Box>
          <Typography {...TYPOGRAPHY.fieldLabel} sx={{ mb: 1.5 }}>
            File Material
          </Typography>
          <Controller
            name="sourceFile"
            control={control}
            rules={{ required: "Source material file is required" }}
            render={({ field }) => (
              <Box
                component="label"
                htmlFor="file-upload"
                sx={{
                  border: "2px dashed #D0D5DD",
                  borderRadius: "12px",
                  p: 3,
                  textAlign: "center",
                  mb: SPACING.field,
                  cursor: "pointer",
                  bgcolor: "#F9FAFB",
                  transition: "all 0.2s ease",
                  display: "block",
                  "&:hover": {
                    borderColor: "#4F39F6",
                    bgcolor: "#F4F3FF",
                  },
                }}
              >
                <FileIcon sx={{ fontSize: "40px", color: "#667085", mb: 1 }} />
                <Typography
                  variant="body2"
                  sx={{
                    color: "#344054",
                    fontWeight: 500,
                    mb: 0.5,
                  }}
                >
                  Click to upload or drag and drop
                </Typography>
                <Typography
                  variant="caption"
                  sx={{
                    color: "#667085",
                    fontSize: "12px",
                  }}
                >
                  TXT, PDF, DOC, DOCX, CSV, JSON, MD (MAX. 10MB)
                </Typography>
                <input
                  {...field}
                  type="file"
                  accept=".txt,.pdf,.doc,.docx,.csv,.json,.md"
                  style={{ display: "none" }}
                  id="file-upload"
                />
              </Box>
            )}
          />
        </Box>
      )}

      {/* ========== FOCUS KEYWORD ========== */}
      <Typography {...TYPOGRAPHY.fieldLabel} sx={{ mb: 1.5 }}>
        Focus Keyword / Topic {isBlogType && "(Important for SEO)"}
      </Typography>
      <Controller
        name="focusKeyword"
        control={control}
        render={({ field }) => (
          <TextField
            {...field}
            fullWidth
            placeholder="e.g., GitHub Actions CI/CD or Repository Forks"
            sx={{
              mb: SPACING.field,
              "& .MuiOutlinedInput-root": {
                borderRadius: "12px",
                "&:hover fieldset": {
                  borderColor: "#4F39F6",
                },
                "&.Mui-focused fieldset": {
                  borderColor: "#4F39F6",
                },
              },
            }}
          />
        )}
      />

      {/* ========== CONTENT TYPE ========== */}
      <Typography {...TYPOGRAPHY.fieldLabel} sx={{ mb: 1.5 }}>
        Content Type
      </Typography>
      <FormControl
        fullWidth
        sx={{
          mb: SPACING.field,
          "& .MuiOutlinedInput-root": {
            borderRadius: "12px",
            "&:hover fieldset": {
              borderColor: "#4F39F6",
            },
            "&.Mui-focused fieldset": {
              borderColor: "#4F39F6",
            },
          },
        }}
      >
        <Select
          value={questionTypeOptions[0].value}
          disabled
          sx={{
            "&.Mui-disabled": {
              backgroundColor: "#F9FAFB",
              color: "#667085",
            },
          }}
        >
          {questionTypeOptions.map((option) => (
            <MenuItem key={option.value} value={option.value}>
              {option.label}
            </MenuItem>
          ))}
        </Select>
      </FormControl>

      {/* ========== BLOG SPECIFIC FIELDS ========== */}
      {isBlogType && (
        <Box sx={{ display: "flex", gap: 2, mb: SPACING.field }}>
          <Box sx={{ flex: 1 }}>
            <Typography {...TYPOGRAPHY.fieldLabel} sx={{ mb: 1.5 }}>
              Blog Length
            </Typography>
            <Controller
              name="blogLength"
              control={control}
              render={({ field }) => (
                <FormControl
                  fullWidth
                  sx={{
                    "& .MuiOutlinedInput-root": {
                      borderRadius: "12px",
                      "&:hover fieldset": {
                        borderColor: "#4F39F6",
                      },
                      "&.Mui-focused fieldset": {
                        borderColor: "#4F39F6",
                      },
                    },
                  }}
                >
                  <Select {...field}>
                    <MenuItem value="short">Short (300-500 words)</MenuItem>
                    <MenuItem value="medium">Medium (500-1000 words)</MenuItem>
                    <MenuItem value="long">Long (1000-2000 words)</MenuItem>
                  </Select>
                </FormControl>
              )}
            />
          </Box>

          <Box sx={{ flex: 1 }}>
            <Typography {...TYPOGRAPHY.fieldLabel} sx={{ mb: 1.5 }}>
              Writing Tone
            </Typography>
            <Controller
              name="writingTone"
              control={control}
              render={({ field }) => (
                <FormControl
                  fullWidth
                  sx={{
                    "& .MuiOutlinedInput-root": {
                      borderRadius: "12px",
                      "&:hover fieldset": {
                        borderColor: "#4F39F6",
                      },
                      "&.Mui-focused fieldset": {
                        borderColor: "#4F39F6",
                      },
                    },
                  }}
                >
                  <Select {...field}>
                    <MenuItem value="professional">Professional</MenuItem>
                    <MenuItem value="casual">Casual</MenuItem>
                    <MenuItem value="technical">Technical</MenuItem>
                    <MenuItem value="conversational">Conversational</MenuItem>
                  </Select>
                </FormControl>
              )}
            />
          </Box>
        </Box>
      )}

      {/* ========== QUESTION TYPES FIELDS ========== */}
      {!isBlogType && !isVideoType && (
        <Box sx={{ display: "flex", gap: 2, mb: SPACING.field }}>
          {showQuestionCount && (
            <Box sx={{ flex: 1 }}>
              <Typography {...TYPOGRAPHY.fieldLabel} sx={{ mb: 1.5 }}>
                Question Count
              </Typography>
              <Controller
                name="questionCount"
                control={control}
                render={({ field }) => (
                  <FormControl
                    fullWidth
                    sx={{
                      "& .MuiOutlinedInput-root": {
                        borderRadius: "12px",
                        "&:hover fieldset": {
                          borderColor: "#4F39F6",
                        },
                        "&.Mui-focused fieldset": {
                          borderColor: "#4F39F6",
                        },
                      },
                    }}
                  >
                    <Select {...field}>
                      {[1, 2, 3, 4, 5].map((count) => (
                        <MenuItem key={count} value={count}>
                          {count}
                        </MenuItem>
                      ))}
                    </Select>
                  </FormControl>
                )}
              />
            </Box>
          )}

          {showDifficultyLevel && (
            <Box sx={{ flex: 1 }}>
              <Typography {...TYPOGRAPHY.fieldLabel} sx={{ mb: 1.5 }}>
                Difficulty Level
              </Typography>
              <Controller
                name="difficultyLevel"
                control={control}
                render={({ field }) => (
                  <FormControl
                    fullWidth
                    sx={{
                      "& .MuiOutlinedInput-root": {
                        borderRadius: "12px",
                        "&:hover fieldset": {
                          borderColor: "#4F39F6",
                        },
                        "&.Mui-focused fieldset": {
                          borderColor: "#4F39F6",
                        },
                      },
                    }}
                  >
                    <Select {...field}>
                      <MenuItem value="Easy">Easy</MenuItem>
                      <MenuItem value="Medium">Medium</MenuItem>
                      <MenuItem value="Hard">Hard</MenuItem>
                    </Select>
                  </FormControl>
                )}
              />
            </Box>
          )}
        </Box>
      )}

      {/* ========== OPTIONS COUNT ========== */}
      {showOptionsCount && (
        <>
          <Typography {...TYPOGRAPHY.fieldLabel} sx={{ mb: 1.5 }}>
            Options Count
          </Typography>
          <Controller
            name="optionsCount"
            control={control}
            render={({ field }) => (
              <FormControl
                fullWidth
                sx={{
                  mb: SPACING.field,
                  "& .MuiOutlinedInput-root": {
                    borderRadius: "12px",
                    "&:hover fieldset": {
                      borderColor: "#4F39F6",
                    },
                    "&.Mui-focused fieldset": {
                      borderColor: "#4F39F6",
                    },
                  },
                }}
              >
                <Select {...field}>
                  {[2, 3, 4, 5].map((count) => (
                    <MenuItem key={count} value={count}>
                      {count}
                    </MenuItem>
                  ))}
                </Select>
              </FormControl>
            )}
          />
        </>
      )}

      {/* ========== ACTION BUTTONS ========== */}
      <Box
        sx={{
          mt: 5,
          pt: 3,
          borderTop: "1px solid #EAECF0",
          display: "flex",
          gap: 2,
          justifyContent: "flex-end"
        }}
      >
        <Button
          onClick={onClose}
          variant="outlined"
          disabled={isLoading}
          sx={{
            minWidth: 120,
            height: "44px",
            borderRadius: "10px",
            textTransform: "none",
            fontWeight: 500,
            fontSize: "14px",
            borderColor: "#D0D5DD",
            color: "#344054",
            "&:hover": {
              borderColor: "#98A2B3",
              backgroundColor: "#F9FAFB",
            },
          }}
        >
          Cancel
        </Button>
        <Button
          type="submit"
          variant="contained"
          disabled={isLoading}
          startIcon={
            isLoading ? (
              <CircularProgress size={20} color="inherit" />
            ) : (
              <AutoAwesomeIcon sx={{ fontSize: "18px" }} />
            )
          }
          sx={{
            minWidth: 180,
            height: "44px",
            borderRadius: "10px",
            textTransform: "none",
            fontWeight: 600,
            fontSize: "14px",
            backgroundColor: "#4F39F6",
            boxShadow: "0px 1px 2px rgba(16, 24, 40, 0.05)",
            "&:hover": {
              backgroundColor: "#3D2BC4",
              boxShadow: "0px 4px 8px rgba(79, 57, 246, 0.2)",
            },
            "&:disabled": {
              backgroundColor: "#D0D5DD",
              color: "#98A2B3",
            },
          }}
        >
          {isLoading ? "Generating..." : "Generate with AI"}
        </Button>
      </Box>
    </form>
  );
};

export default QuestionConfigurator;
